version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432" # El puerto original del host mapeado al puerto por defecto de PostgreSQL
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  new_db:
    image: postgres:latest
    ports:
      - "5433:5432" # Un puerto diferente en el host para evitar conflictos
    env_file:
      - .env
    volumes:
      - new_postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  new_postgres_data:
